# Generated by Django 3.1.1 on 2021-03-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_permissionlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionlist',
            options={'permissions': (('create_test_case', '创建测试用例'), ('edit_test_case', '编辑测试用例'), ('delete_test_case', '删除测试用例'), ('view_test_case', '查看测试用例'), ('create_env_config', '创建环境配置'), ('edit_env_config', '编辑环境配置'), ('delete_env_config', '删除环境配置'), ('view_env_config', '查看环境配置'))},
        ),
    ]
